In [3]:
from bike_utils import get_dock_availability, get_marker_color, query_station_status, get_bike_availability, get_station_latlon, join_latlon, run_osrm , geocode  # Import custom utils functions

2025-04-25 11:31:47.403 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

In [1]:
station_url = 'https://tor.publicbikesystem.net/ube/gbfs/v1/en/station_status.json'  
latlon_url = "https://tor.publicbikesystem.net/ube/gbfs/v1/en/station_information"

In [4]:
data_df = query_station_status(station_url)  # Get station status data
latlon_df = get_station_latlon(latlon_url)

2025-04-25 11:31:53.826 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2025-04-25 11:31:53.826 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-25 11:31:54.041
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run c:\Users\yuxz\AppData\Local\miniconda3\envs\full_stack\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2025-04-25 11:31:54.041 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-25 11:31:54.041 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-25 11:31:54.555 Thread 'Thread-3': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-25 11:31:54.556 Thread 'Thread-3': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-25 11:31:55.951 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2025-04-25 11:31:55.952 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [5]:
data_df.head()

,station_id,num_bikes_available,num_bikes_available_types,num_bikes_disabled,num_docks_available,num_docks_disabled,last_reported,is_charging_station,status,is_installed,is_renting,is_returning,traffic,mechanical,ebike
time,,,,,,,,,,,,,,,
2025-04-25 03:31:46+00:00,7000,39,"{'mechanical': 36, 'ebike': 3}",3,5,0,2025-04-25 03:31:26,False,IN_SERVICE,1,1,1,None,36,3
2025-04-25 03:31:46+00:00,7001,0,"{'mechanical': 0, 'ebike': 0}",6,17,0,2025-04-25 03:30:52,True,IN_SERVICE,1,1,1,None,0,0
2025-04-25 03:31:46+00:00,7002,0,"{'mechanical': 0, 'ebike': 0}",4,15,0,2025-04-25 03:29:25,False,IN_SERVICE,1,1,1,None,0,0
2025-04-25 03:31:46+00:00,7003,1,"{'mechanical': 1, 'ebike': 0}",2,11,1,2025-04-25 03:29:25,False,IN_SERVICE,1,1,1,None,1,0
2025-04-25 03:31:46+00:00,7005,1,"{'mechanical': 1, 'ebike': 0}",1,21,0,2025-04-25 03:29:03,False,IN_SERVICE,1,1,1,None,1,0

In [6]:
latlon_df.head()

,station_id,name,physical_configuration,lat,lon,altitude,address,capacity,is_charging_station,rental_methods,groups,obcn,short_name,nearby_distance,_ride_code_support,rental_uris,post_code,is_valet_station,cross_street
0,7000,Fort York Blvd / Capreol Ct,REGULAR,43.639832,-79.395954,NaN,Fort York Blvd / Capreol Ct,47,False,"[KEY, TRANSITCARD, CREDITCARD, PHONE]","[South, Fort York - Entertainment District]",647-643-9607,647-643-9607,500.0,True,{},NaN,NaN,NaN
1,7001,Wellesley Station Green P,ELECTRICBIKESTATION,43.664964,-79.383550,NaN,Yonge / Wellesley,23,True,"[KEY, TRANSITCARD, CREDITCARD, PHONE]","[E-Charging , South, Church Wellesley / Yorkvi...",416-617-9576,416-617-9576,500.0,True,{},M4Y 1G7,NaN,NaN
2,7002,St. George St / Bloor St W,REGULAR,43.667131,-79.399555,NaN,St. George St / Bloor St W,19,False,"[KEY, TRANSITCARD, CREDITCARD, PHONE]","[South, U of T - Hospital Row]",647-643-9615,647-643-9615,500.0,True,{},NaN,NaN,NaN
3,7003,Madison Ave / Bloor St W,REGULAR,43.667018,-79.402796,NaN,Madison Ave / Bloor St W,15,False,"[KEY, TRANSITCARD, CREDITCARD, PHONE]","[South, Bloor St W / Annex]",647-631-4587,647-631-4587,500.0,True,{},NaN,NaN,NaN
4,7005,King St W / York St,REGULAR,43.648001,-79.383177,0.0,King St W / York St,23,False,"[KEY, TRANSITCARD, CREDITCARD, PHONE]","[South, Financial District]",647-643-9693,647-643-9693,500.0,True,{},NaN,NaN,NaN

In [ ]:
import requests

city_gbfs_url = {"https://tor.publicbikesystem.net/ube/gbfs/v1/en/station_information.json"
}
# Main feed URL
gbfs_url = "https://gbfs.divvybikes.com/gbfs/gbfs.json"
feeds = requests.get(gbfs_url).json()
feed_dict = {feed["name"]: feed["url"] for feed in feeds["data"]["en"]["feeds"]}

# Get URLs for station info and station status
station_info_url = feed_dict["station_information"]
station_status_url = feed_dict["station_status"]

In [26]:
# Download both
info = requests.get(station_info_url).json()
status = requests.get(station_status_url).json()
import pandas as pd
# Normalize and merge
info_df = pd.json_normalize(info["data"]["stations"])
status_df = pd.json_normalize(status["data"]["stations"])
df = pd.merge(info_df, status_df, on="station_id")

In [27]:
df.head()

,electric_bike_surcharge_waiver,eightd_has_key_dispenser,lon,eightd_station_services,station_id,external_id,has_kiosk,station_type,name,short_name,...,is_renting,is_installed,num_docks_disabled,last_reported,num_ebikes_available,num_scooters_available,is_returning,eightd_has_available_keys,num_bikes_available,num_scooters_unavailable
0,False,False,-87.703420,[],1936553212713581016,1936553212713581016,False,classic,Kedzie Ave & 52nd St,21384,...,1,1,0,1745561694,0,0.0,1,False,6,0.0
1,False,False,-87.693227,[],1934289944388426278,1934289944388426278,False,classic,Fairfield Ave & 44th St,21380,...,1,1,0,1745561710,9,0.0,1,False,14,0.0
2,False,False,-87.669886,[],a3a965b2-a135-11e9-9cda-0a87ae2ba916,a3a965b2-a135-11e9-9cda-0a87ae2ba916,True,classic,Hermitage Ave & Polk St,13080,...,1,1,0,1745561719,1,1.0,1,False,1,0.0
3,False,False,-87.606615,[],a3ac30c5-a135-11e9-9cda-0a87ae2ba916,a3ac30c5-a135-11e9-9cda-0a87ae2ba916,True,classic,Cottage Grove Ave & 51st St,TA1309000067,...,1,1,0,1745561732,2,1.0,1,False,5,0.0
4,False,False,-87.617000,[],a3a859c4-a135-11e9-9cda-0a87ae2ba916,a3a859c4-a135-11e9-9cda-0a87ae2ba916,True,classic,MLK Jr Dr & 29th St,TA1307000139,...,1,1,0,1745561735,4,1.0,1,False,9,0.0

In [28]:
df[["station_id", "name", "lat", "lon", "num_bikes_available", "num_docks_available"]].head()

,station_id,name,lat,lon,num_bikes_available,num_docks_available
0,1936553212713581016,Kedzie Ave & 52nd St,41.799060,-87.703420,6,9
1,1934289944388426278,Fairfield Ave & 44th St,41.813617,-87.693227,14,0
2,a3a965b2-a135-11e9-9cda-0a87ae2ba916,Hermitage Ave & Polk St,41.871514,-87.669886,1,13
3,a3ac30c5-a135-11e9-9cda-0a87ae2ba916,Cottage Grove Ave & 51st St,41.803038,-87.606615,5,9
4,a3a859c4-a135-11e9-9cda-0a87ae2ba916,MLK Jr Dr & 29th St,41.842052,-87.617000,9,9